own_log = "/tmp/goOpenhab.log"
pid_file = "/tmp/goOpenhab.pid"
do_trace = true
log_severity = 3

logs = [
  "<path to openhab events.log>",
  "<path to openhab openhab.log>"
]

tbtoken = "<tbtoken>"
chatid  = <chatid>

dump_file = "/tmp/goOpenhab.dump"

mqtt_broker = "tcp://<ip of mqtt broker:1883"
# list of topics
topics = [
  "topic1",
  "topic2"
]

rest_url = "http://127.0.0.1:8080/rest"
rest_token = "<openhab token>"
